execution_env=local
#execution_env=remote

appURL1=http://localhost/opencartsite/
appURL2=https://tutorialsninja.com/demo/
email=deekshithakadari7@gmail.com
password=deekshitha
#password=deekshitha1234
searchProductName=iphone